name: Node.js CI
on: 
push:
branches:
- main pull_request:
branches: 
- main schedule: 
- cron: '0 */4 * * *'
jobs:
build: 
runs-on: 
ubuntu-latest strategy:
matrix: 
node-version: 
[20.x] steps: 
- name: Checkout repository
